### ISSUE TITLE
override $sm variable from ng-lib library

### ISSUE THREAD

**Issue by UseMuse** [aboudard/ng-library-schematics#1]
how to override the $sm variable from the ng-lib library in sandbox, so that the styles already use the new value of the $sm variable?

**Comment by aboudard** [comment]
Hello, from my perspective, you would have to override the variable BEFORE building the css of the library.
That means the architecture of the files would look different than my example here. Does that make sense for you ?

**Comment by UseMuse** [comment]
I would like to, the library has a certain set of styles that are based on the list of scss variables (in this library).
I would like to redefine the library's scss variables in a project using this library in order to change the color palette of the library's styles.
